defmodule Mix.Tasks.PhoenixCap.UpdateAssets do
  @moduledoc """
  Updates bundled Cap widget and WASM assets from npm.

      mix phoenix_cap.update_assets
      mix phoenix_cap.update_assets --widget latest --wasm latest
      mix phoenix_cap.update_assets --widget 0.1.50 --wasm 0.0.7
      mix phoenix_cap.update_assets --no-wasm

  The task intentionally uses `npm pack` instead of depending on a JavaScript
  package manager layout in this repository. It copies only the files
  PhoenixCap vendors.
  """

  use Mix.Task

  @shortdoc "Updates bundled Cap widget and WASM assets"

  @widget_package "@cap.js/widget"
  @wasm_package "@cap.js/wasm"

  @widget_files [
    {"cap.min.js", "cap.min.js"},
    {"cap.compat.min.js", "cap.compat.min.js"},
    {"cap-floating.min.js", "cap-floating.min.js"},
    {"cap.d.ts", "cap.d.ts"},
    {"wasm-hashes.min.js", "wasm-hashes.min.js"},
    {"LICENSE", "CAP_WIDGET_LICENSE"}
  ]

  @wasm_files [
    {"browser/cap_wasm_bg.wasm", "wasm/cap_wasm_bg.wasm"},
    {"browser/cap_wasm.js", "wasm/cap_wasm.js"},
    {"browser/cap_wasm.d.ts", "wasm/cap_wasm.d.ts"},
    {"browser/cap_wasm_bg.wasm.d.ts", "wasm/cap_wasm_bg.wasm.d.ts"}
  ]

  @impl Mix.Task
  def run(args) do
    {opts, _argv, invalid} =
      OptionParser.parse(args,
        strict: [
          widget: :string,
          wasm: :string,
          assets_dir: :string,
          no_wasm: :boolean
        ]
      )

    if invalid != [] do
      Mix.raise("Invalid options: #{inspect(invalid)}")
    end

    assets_dir = Keyword.get(opts, :assets_dir, "assets")
    widget_version = Keyword.get(opts, :widget, "latest")
    wasm_version = Keyword.get(opts, :wasm, "latest")
    include_wasm? = !Keyword.get(opts, :no_wasm, false)

    File.mkdir_p!(assets_dir)

    widget = update_package!(@widget_package, widget_version, assets_dir, @widget_files)

    wasm =
      if include_wasm? do
        update_package!(@wasm_package, wasm_version, assets_dir, @wasm_files)
      end

    write_versions!(assets_dir, widget, wasm)

    Mix.shell().info("Updated Cap assets in #{assets_dir}")
    Mix.shell().info("  widget: #{widget.version}")

    if wasm do
      Mix.shell().info("  wasm:   #{wasm.version}")
    end
  end

  defp update_package!(package, requested_version, assets_dir, files) do
    version = resolve_version!(package, requested_version)

    with_tmp_dir(fn tmp_dir ->
      package_dir = download_package!(package, version, tmp_dir)

      Enum.each(files, fn {source, destination} ->
        source_path = Path.join(package_dir, source)
        destination_path = Path.join(assets_dir, destination)

        File.mkdir_p!(Path.dirname(destination_path))
        File.cp!(source_path, destination_path)
      end)

      %{package: package, version: version}
    end)
  end

  defp resolve_version!(package, "latest") do
    case System.cmd("npm", ["view", package, "version"], stderr_to_stdout: true) do
      {version, 0} ->
        version
        |> String.trim()
        |> require_version!(package)

      {output, _status} ->
        Mix.raise("Could not resolve latest #{package} version:\n#{output}")
    end
  end

  defp resolve_version!(_package, version), do: version

  defp require_version!("", package),
    do: Mix.raise("npm returned an empty version for #{package}")

  defp require_version!(version, _package), do: version

  defp download_package!(package, version, tmp_dir) do
    case System.cmd(
           "npm",
           ["pack", "#{package}@#{version}", "--pack-destination", tmp_dir, "--silent"],
           stderr_to_stdout: true
         ) do
      {output, 0} ->
        tgz_name =
          output
          |> String.split("\n", trim: true)
          |> List.last()

        tgz_path = Path.join(tmp_dir, tgz_name)
        unpack_dir = Path.join(tmp_dir, "unpacked")
        File.mkdir_p!(unpack_dir)

        :ok =
          tgz_path
          |> String.to_charlist()
          |> :erl_tar.extract([:compressed, {:cwd, String.to_charlist(unpack_dir)}])

        Path.join(unpack_dir, "package")

      {output, _status} ->
        Mix.raise("Could not download #{package}@#{version}:\n#{output}")
    end
  end

  defp write_versions!(assets_dir, widget, nil) do
    File.write!(Path.join(assets_dir, "VERSIONS"), """
    # Generated by mix phoenix_cap.update_assets
    #{@widget_package}=#{widget.version}
    """)
  end

  defp write_versions!(assets_dir, widget, wasm) do
    File.write!(Path.join(assets_dir, "VERSIONS"), """
    # Generated by mix phoenix_cap.update_assets
    #{@widget_package}=#{widget.version}
    #{@wasm_package}=#{wasm.version}
    """)
  end

  defp with_tmp_dir(fun) do
    tmp_dir =
      Path.join(System.tmp_dir!(), "phoenix_cap_assets_#{System.unique_integer([:positive])}")

    File.mkdir_p!(tmp_dir)

    try do
      fun.(tmp_dir)
    after
      File.rm_rf!(tmp_dir)
    end
  end
end
